/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: c1563a0280503459ecaaa834261db7d0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ContainerClass";
	}
	interface Env {
		CONTAINER_DO: DurableObjectNamespace<import("./src/index").ContainerClass>;
	}
}
interface Env extends Cloudflare.Env {}
